### ISSUE TITLE
Replication blues and the mystery of 'uptodate' status.

### ISSUE THREAD

**Issue by SukantGujar** [colinskow/pouch-mirror#1]
Hi Colin,

Aside from Superlogin, I am also trying to integrate pouch-mirror into my application to sync with a logged in user's remote private DB (CouchDB 1.6.1) with an IndexedDB based in-browser PouchDB instance. 

My setup is something like this -
Front end - React, Reflux, superlogin-client and pouch-mirror.
Server - Express, Superlogin
DB - Couch 1.6.1 (brand new, Admin Party enabled).

Right now, when I am using pouch-mirror, its able to write docs to the user's remoteDB correctly, when the sync has not finished. However, the sync never finishes. The replication process keeps on throwing 'ETIMEDOUT' exception (caught in the `error` event handler in `startLiveReplication`). Due to this issue, the replication to local DB _never _ completes and the application keeps on using remoteDB only. 
Using Fiddler, I saw that the request to the Remote URL look like this -

```
GET http://localhost:5984/<remoteDBname>/_changes?timeout=25000&style=all_docs&feed=longpoll&heartbeat=10000&since=3&limit=100 HTTP/1.1
Host: localhost:5984
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json
Origin: http://localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
Authorization: Basic Wl9zQ0dKZFNSa2FmNm9wOUcxQ0xwZzp0MWlqbUJCQlNJbUMyMVpfV1U1bjln
Referer: http://localhost:8080/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8

```

Its on this request where pouch-mirror receives the time-out exception. I take it that this is supposed to be a long-polling request and wonder whether this exception is expected.

I looked into the code of `startLiveReplication` and saw that there's a bind to `uptodate` event which is supposed to handle sync completion as its this place where pouch-mirror switches remoteDB with localDB. However, this enevt never gets invoked. Also, I didn't notice this event in the PouchDB [replication docs](https://pouchdb.com/api.html#replication). There's a `complete` event listed but per the documentation, for a `live` replication, the complete event will never be invoked unless the sync is cancelled.

Thoughts!?

PS: My entire development stack is on a single machine.

**Comment by SukantGujar** [comment]
Update - Found [this](https://github.com/pouchdb/pouchdb/commit/937ef1f68c84e938ce470c8d03966aa917420587). When I changed `uptodate` to `paused` in `startLiveReplication`, the timeout is not happening anymore. Is this a right fix!?

**Comment by colinskow** [comment]
I haven't updated PouchMirror in a while. The PouchDB dependency has had some breaking changes since then. These are probably old PoucDB bugs. I need to update this to use PouchDB 5.3.x.

**Comment by SukantGujar** [comment]
#2 Added PouchDB 5.3.2 compatible sync logic.
