### ISSUE TITLE
Add support for `destroy` method.

### ISSUE THREAD

**Issue by SukantGujar** [colinskow/pouch-mirror#2]
Currently, the pouch-mirror API doesn't include `destroy` event. Can I take a PR to add one? The idea is to destroy localDB instance. This is useful in scenarios where multiple users share one browser environment and when a user logs-off, it is prudent to delete any local DB containing private information. As pouch-mirror abstracts the localDB instance, exposing a destroy method will make it easy to delete the localDB.

**Comment by colinskow** [comment]
While you were at it, it would be great if you would upgrade to `pouchdb ^5.3.2`. I believe the changes API events are different now, so they will need to be updated.

**Comment by colinskow** [comment]
Instead of `destroy` make it `destroyLocal` we don't want to destroy the remote.

**Comment by SukantGujar** [comment]
Yep, I am already using 5.3.2.
On Apr 30, 2016 11:21 PM, Colin Skow notifications@github.com wrote:While you were at it, it would be great if you would upgrade to pouchdb ^5.3.2. I believe the changes API events are different now, so they will need to be updated.

**Comment by colinskow** [comment]
We can call it `destroy` to match the API, but it will only destroy local. Remote stays intact.

**Comment by SukantGujar** [comment]
#3 Added the change.
