### ISSUE TITLE
Enhancement - Local First Mirrorring

### ISSUE THREAD

**Issue by SukantGujar** [colinskow/pouch-mirror#5]
Pouch-mirror uses a remote-first strategy for any edit calls. This ensures that there's only a single source of truth in a multi-client-single-server scenario and also helps with conflict resolution.
But in cases where the client interactions are heavy, the server-first approach may lead to a slower turn-around, and may not work well in cases of flaky network connectivity.

Would you plan to revisit this project to bake-in a local-first strategy? If you are too busy now, I can fork this project and add one.

For a local-first approach, I think the following interactions should be acceptable -
1. On application setup, do a one-time two-way sync with Remote. During this time, redirect all read/writes to the server.
2. Once the sync is complete, switch to local DB. Now all r/w operations happen locally.
3. On every write (to local), schedule a (delayed, say 2-4 seconds) one-time 2-way sync with remote. On conflicts, raise events.
4. If another write occurs before the delayed sync happens, cancel the sync and reschedule it. This way if a lot of writes occur in succession, we don't end-up doing several sync's with the server. Basically we wait for things to cool down on the client before firing up the remote sync.
5. Before local destroy, offer a configurable replication to remote. This way scenarios like 'logout' which invoke destroy can rest in peace knowing the localDB will replicate to remote before being wiped.

Thoughts!?

**Comment by colinskow** [comment]
I like the idea. We can have a configuration option `sourceOfTruth` which can be `'remote'` or `'local'`. The default is remote.

I also want to add an option to specify the adapter to use for the local database.

Go ahead and submit a PR. I am going to merge your first PR over the next couple days with some minor changes. You may want to wait until that is complete before forking so you don't have to resolve git conflicts later.

**Comment by colinskow** [comment]
The delay should be configurable in the options with a default of no delay.

**Comment by colinskow** [comment]
Your PR #3 is now merged on a local branch. But I am going to do a complete re-write of PouchMirror as a PouchDB plugin. This will make it practically maintenance free and will transparently pass through any functionality not handled by PouchMirror to the local db.

Wait until this is done before you start working on anything.

**Comment by colinskow** [comment]
@SukantGujar check out the new release! I think you're going to like it. Every function, including plugins, will now pass through to `localDB` if PouchMirror hasn't overridden it. I also added browser support.
